### ISSUE TITLE
Schedule Weekly Staff Meeting

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi17#12]
I'm thinking Tuesdays @ 1:00.  With class ending at 12:00, that'd give us time to eat before the meeting.

Conflicts with that time?

**Comment by emjun** [comment]
1pm Tuesdays work for me!

**Comment by esc11** [comment]
No conflicts!

**Comment by karkar** [comment]
Works out fine with Change seminar during 12-1.

**Comment by d-dw** [comment]
That should work for me as well!

**Comment by jayfo** [comment]
Wow this worked out easy.

I'm going to schedule this for Tuesdays at 1:00 to 2:30.

I'm then going to schedule my office hour Tuesdays 2:30 to 3:30.

I'll send an email / calendar invite.

**Comment by jayfo** [comment]
Scheduled and calendar invite sent.
