### ISSUE TITLE
Schedule and Post Office Hours

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi17#13]
I'd like David and Eunice to each hold an office hour.

We need to coordinate on scheduling that, and book a room.

**Comment by emjun** [comment]
@jayfo Are you thinking David and I hold one hour each?

David - I am free Wednesday mornings, Wednesday early afternoons,  and Thursday afternoons. 
Once we decide times, I can book a room for us.

**Comment by d-dw** [comment]
@emjun I'm thinking it might make sense for us to hold office hours on separate days to allow for more options.

In any case, Wednesday in the afternoons (say, at 3pm) or Thursdays after class would be good times for me.

**Comment by jayfo** [comment]
I've scheduled and posted for Tuesdays @ 2:30.

@emjun @d-dw 

I agree it's best for one of you to hold an hour on Wednesday, the other on Thursday.  It's also good if the Thursday time is not @ 2:30 (because anybody who has a schedule conflict with my Tuesday hour will probably also have that same conflict on Thursdays, really limiting their access).

CSE 218 / CSE 220 are good for this, and there's still a lot of availability. So can you two "call it" for times? We'll have more trouble securing a good room if we wait until next week.

**Comment by d-dw** [comment]
@emjun It sounds like we need to pick one of the following:
1) I hold an hour Wednesday at 3pm and you hold one sometime Thursday.
2) I hold an hour Thursday at 12pm and you hold one sometime Wednesday.

Either works for me, although Thursday might be slightly better.

**Comment by emjun** [comment]
Ok! Let's do...
Wednesday 1:45pm - 2:45pm Eunice
Thursday 12pm - 1pm David 

Shall we go with this? @d-dw

**Comment by d-dw** [comment]
Sounds good!

**Comment by emjun** [comment]
Just reserved CSE 021 for Eunice 1:45pm - 2:45pm Wednesdays and David 12pm - 1pm!

**Comment by jayfo** [comment]
Fun fact about the CSE calendar. If you book as <String>, it'll show "<Name> - <String>". So you don't have to type your own name in. But if you want it to just display <String>, you prefix it wish a "-", like "-String". Very helpful when making bookings for other people.

**Comment by jayfo** [comment]
Posted the office hours in #28.

Decided there's no need for hours in the first week. Let's focus that time on getting ahead in preparation, as Week 2 is very intense due to the project bidding / matching process.
