### ISSUE TITLE
Check Index Page: Clear "Under Construction" Notice

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi17#14]
I think this page is ready to go, pending the handful of explicit TODO that are marked as `code` within it.

https://courses.cs.washington.edu/courses/cse440/17wi/

If people can confirm it looks ready to go, I'll remove the top disclaimer.

**Comment by d-dw** [comment]
There is strange wording in the first paragraph under Course Description. Recommend deleting the first sentence.

**Comment by jayfo** [comment]
Whoops, thanks @d-dw for catching that copy-paste bug.

**Comment by jayfo** [comment]
I'm considering this closed based on #29.
