### ISSUE TITLE
Add Staff to Canvas

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi17#18]

**Comment by karkar** [comment]
@jayfo Do we need to do anything for this?

**Comment by jayfo** [comment]
I've added David, Elisabeth, Ravi.

I couldn't find a NetID for Eunice?  @emjun?

**Comment by emjun** [comment]
Yes! "emjun" is my UW NetID

**Comment by jayfo** [comment]
Added everybody.
