### ISSUE TITLE
Schedule Kickoff Staff Meeting

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi17#21]
When are people back / available for a longer kickoff meeting to get organized?

Monday 1/2 is a holiday. I'm personally willing, but understand people may not be here.

Another option is the afternoon of Tuesday 1/3?

**Comment by karkar** [comment]
Am available anytime.

**Comment by emjun** [comment]
I am available Monday all day.

Tuesday - I have two doctors' appointments: 10am - 11am, 3pm - 4pm. Would need to leave about 10 minutes before those. Also, could come to lecture late on Tuesday.

**Comment by esc11** [comment]
I'll be back in Seattle on the 31st, and both of those dates will work for me.

**Comment by d-dw** [comment]
I am available starting Tuesday 1/3, and will be available throughout the week during the daytime (before 6pm).

**Comment by jayfo** [comment]
Great, let's do this Tuesday 1/3 starting at 1:00.

I'll send a calendar until 5:00.  It's unimaginable to me that we'll meet the whole time (and I see that Eunice will need to go for her 3:00), but this block will allow us to sort out everything to get the course started.

**Comment by jayfo** [comment]
Scheduled and calendar invite sent.
