### ISSUE TITLE
Revise Assignment 4

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi17#22]

**Comment by d-dw** [comment]
I took a look at the assignments, and they look fairly straightforward. I have two minor concerns:

1) Did we want to modify the contextual inquiry / research assignments? I know we talked briefly about this during our meeting. Did you want to make the assignment more flexible?

2) The final two weeks seem tight with 3e, 3f, and the website, video, and poster deliverables coming soon after. Was this generally OK before?

**Comment by jayfo** [comment]
Yes, revising assignment 2 for more flexibility is in my todo here. I've renamed it "design research" from "contextual inquiry", and will update text too.

I decided to move 4a back a few days. It makes the deadlines closer to each other, but I think actually gives them more flexibiilty in pulling together the final deliverables.

**Comment by jayfo** [comment]
Partially resolved, remnant in #99.
