### ISSUE TITLE
Revise and Post Readings

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi17#23]

**Comment by d-dw** [comment]
I will likely have other reading suggestions, but as of now I can think of the following:

1) For contextual inquiry, it might be useful to introduce the concept of distributed cognition. Although, it could be difficult to understand. http://mcs.open.ac.uk/yr258/papers/dcog/dcog-brief-intro.pdf

2) Along the lines of quantified self, I think the short story by Ray Bradbury 'There will come soft rains' might be relevant. http://www.gs.cidsnet.de/englisch-online/originals/soft_rains.htm (Better source likely needed)

**Comment by jayfo** [comment]
Posted Reading 1, as a minor update to prior version.

**Comment by jayfo** [comment]
#83 is now the final of these.
