### ISSUE TITLE
Add Staff to GitHub Organization

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi17#24]
If you comment here, I'll get your GitHub ID and add you to the organization.

**Comment by karkar** [comment]
@jayfo

**Comment by emjun** [comment]
Hi!

**Comment by esc11** [comment]
Elisabeth here!

**Comment by d-dw** [comment]
This is David!

**Comment by jayfo** [comment]
Everybody should have an invite now.

No idea what happens when you accept, but let's do that.  :)
