### ISSUE TITLE
Calendar Presentations

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi17#36]
Reminder we want to plan as-many-as-possible of us in the Friday sections on Feb 10 and Mar 3.

This is for the Assignment 2 and Assignment 3 presentations.  I've put these on my calendar.

Reply that you've put them on yours, and we'll close this.

**Comment by emjun** [comment]
On le calendar!

**Comment by d-dw** [comment]
Yep, on the calendar.

**Comment by karkar** [comment]
Done.

**Comment by esc11** [comment]
Done, and I can go to the 11:30-12:20 section on 2/10!
