### ISSUE TITLE
Email Readings to TA

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi17#37]

**Comment by jayfo** [comment]
@karkar

**Comment by karkar** [comment]
@jayfo got it

**Comment by karkar** [comment]
@jayfo added to google drive, you can close it now.

**Comment by jayfo** [comment]
So you have a Google Drive going now too?

I thought that was just going to be the slides, using Dropbox for other stuff?  I'm worried about having too many things going and us not knowing where things are.  So keep an eye out for that.
