### ISSUE TITLE
Eunice Accept Team Invite

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi17#47]
@emjun still appears as pending here:

https://github.com/orgs/uwcse440/teams/winter-2017-staff

**Comment by emjun** [comment]
Odd! I thought I joined over winter break. Can you send me the invite link again? The link you just shared with me is broken?

**Comment by emjun** [comment]
I'm in now!

**Comment by jayfo** [comment]
Yay!
