### ISSUE TITLE
Consider Additions / Revisions to Mockup Tools

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi17#65]
Current set is:

```
   Some recommendations from the course staff include:
   
   - [Adobe Illustrator](http://www.adobe.com/products/illustrator.html)
   - [Axure](http://www.axure.com/)
   - [Balsamiq](https://balsamiq.com/)   
   - [Omnigraffle](http://www.omnigroup.com/omnigraffle)
   - [InkScape](http://www.inkscape.org/en/)
   - [Microsoft Visio](http://office.microsoft.com/en-us/visio/)
```

**Comment by d-dw** [comment]
Two others to add:
Indigo Studio. Free Academic License: http://www.infragistics.com/products/indigo-studio/indigo-academic-license
Adobe Experience Design CC Preview: http://www.adobe.com/products/experience-design.html

**Comment by esc11** [comment]
Vectr (web-based): https://vectr.com/
Figma (for real-time collaboration): https://www.figma.com/

**Comment by jayfo** [comment]
Added in #70.
