### ISSUE TITLE
Finalize Assignment 3

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-wi17#67]
I went through and revised Assignment 3:

https://github.com/uwcse440/web-cse440-wi17/pull/66/files

Check it for any 'bugs' before I remove the 'under construction' warning at the top?

http://courses.cs.washington.edu/courses/cse440/17wi/calendar.html

http://courses.cs.washington.edu/courses/cse440/17wi/assignments/assignment3/

**Comment by emjun** [comment]
I just took a look through the assignment. It looks pretty good to me, but I did have some questions about what section will look like these weeks, but I think we can discuss this in a staff meeting. I didn't catch any bugs the first time through.

**Comment by d-dw** [comment]
Looks good.

**Comment by jayfo** [comment]
Done in #70.
